project:
  type: website
  output-dir: docs

website:
  site-url: "https://sanaz01.github.io/"
  google-analytics:
    tracking-id: "G-PHD8FEK27R"
  title: "Sanaz Agarwal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blogs.qmd
      - publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

