project:
  type: website
  output-dir: docs

website:
  title: "Sanaz Agarwal"
  open-graph: true
  cookie-consent: true
  google-analytics:
    tracking-id: "G-PHD8FEK27R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blogs.qmd
      - publications.qmd
      # link to resume?
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

