project:
  type: website
  output-dir: docs

website:
  site-url: "https://sanaz01.github.io/"
  description: "Sanaz Agarwal's personal website" 
  google-analytics:
    tracking-id: "G-PHD8FEK27R"
  title: "Sanaz Agarwal"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - blogs.qmd
      - publications.qmd
      - research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

